import { useEffect, useState, type ReactNode } from "react";
import { Link } from "wouter";
import { Bell, BookOpen, ChevronDown, ChevronRight, Command, Menu, MoreHorizontal, Search, X, ArrowUpRight, GitBranch, HeartHandshake } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog";
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { BRANCHES } from "@/data/demo";
import { CHURCH_NAME, NAV_ITEMS, PASTOR_NAME, type Section } from "@/data/navigation";

export const DashboardShell = ({ activeSection, scope, onScope, onSearch, onNavigate, children }: {
  activeSection: Section; scope: number | "global"; onScope: (scope: number | "global") => void;
  onSearch: () => void; onNavigate: (section: Section) => void; children: ReactNode;
}) => {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const title = NAV_ITEMS.find(item => item.label === activeSection)?.title;
  useEffect(() => { setMobileOpen(false); window.scrollTo({ top: 0, behavior: "instant" }); }, [activeSection]);
  const logo = (id: string) => <Link href="/" className="church-brand" data-testid={`${id}-brand-link`} aria-label="Heirs of Promise dashboard"><span className="church-brand-mark"><BookOpen size={23} strokeWidth={1.6} /></span><span><strong>HEIRS OF PROMISE</strong><small>Sanctuary · Church workspace</small></span></Link>;
  const menu = (id: string) => <><div className="sidebar-church" data-testid={`${id}-church-info`}><span>YOUR COMMUNITY</span><strong>{CHURCH_NAME}</strong><small><span className="tiny-dot" />5 branches, one family</small></div><nav className="church-main-nav" aria-label={`${id === "desktop" ? "Main" : "Mobile"} navigation`}><span className="nav-label" data-testid={`${id}-workspace-label`}>WORKSPACE</span>{NAV_ITEMS.map(({ label, title: itemTitle, path, icon: Icon }, i) => <Link href={path} key={label} data-testid={`${id}-nav-${label.toLowerCase().replace(/ /g, "-")}`} onClick={() => setMobileOpen(false)} className={`church-nav-item ${activeSection === label ? "active" : ""} ${i === 8 ? "nav-group-start" : ""}`} aria-current={activeSection === label ? "page" : undefined}><Icon size={19} strokeWidth={1.65} /><span>{itemTitle}</span>{activeSection === label && <i />}</Link>)}</nav><div className="church-sidebar-footer"><HeartHandshake size={20} /><p data-testid={`${id}-sidebar-purpose`}>A place for every person.<br /><strong>A purpose for every team.</strong></p></div><button className="church-profile" data-testid={`${id}-profile-button`} onClick={() => { setMobileOpen(false); setProfileOpen(true); }}><span className="profile-avatar">DS</span><span><strong>{PASTOR_NAME}</strong><small>Church administrator</small></span><ChevronRight size={15} /></button></>;
  return <div className="app-shell light-shell" data-testid="dashboard-shell">
    <aside className="church-sidebar">{logo("desktop")}{menu("desktop")}</aside>
    <main className="main-content"><header className="church-topbar"><div className="desktop-breadcrumb" data-testid="workspace-breadcrumb"><span>Workspace</span><ChevronRight size={14} /><strong>{title}</strong></div><div className="mobile-church-header"><button className="icon-button" data-testid="mobile-menu-open" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu size={23} /></button>{logo("mobile")}</div>
      <div className="church-topbar-actions"><button className="church-search-button" data-testid="global-search-btn" aria-label="Search the workspace" onClick={onSearch}><Search size={17} /><span>Search your workspace…</span><kbd><Command size={11} /> K</kbd></button>
      <Popover open={notificationsOpen} onOpenChange={setNotificationsOpen}><PopoverTrigger asChild><button className="icon-button church-notification-button" data-testid="notifications-button" aria-label="View notifications"><Bell size={20} /><i /></button></PopoverTrigger><PopoverContent className="workspace-popover" align="end" data-testid="notifications-popover"><h2 data-testid="notifications-heading">A few things to keep close.</h2><button data-testid="notification-care-link" onClick={() => { setNotificationsOpen(false); onNavigate("Care inbox"); }}><HeartHandshake size={18} /><span><strong>Make time for a check-in</strong><small>View prayer requests and care follow-ups.</small></span><ArrowUpRight size={16} /></button><button data-testid="notification-events-link" onClick={() => { setNotificationsOpen(false); onNavigate("Events"); }}><BookOpen size={18} /><span><strong>Your next gathering</strong><small>Explore what's coming up in your church.</small></span><ArrowUpRight size={16} /></button></PopoverContent></Popover>
      <button className="topbar-profile-button" data-testid="topbar-profile-button" aria-label="Open pastor profile" onClick={() => setProfileOpen(true)}><span className="profile-avatar">DS</span><ChevronDown size={13} /></button></div></header>
      <div className="workspace-context-bar"><span data-testid="workspace-context-name">{CHURCH_NAME}<span className="context-separator">/</span><strong>{title}</strong></span><label className="scope-selector"><GitBranch size={14} /><select aria-label="Choose branch scope" data-testid="branch-scope-select" value={scope} onChange={e => onScope(e.target.value === "global" ? "global" : Number(e.target.value))}><option value="global">All branches</option>{BRANCHES.map((branch, i) => <option key={branch} value={i + 1}>{branch}</option>)}</select></label></div>
      <div className="page-content">{children}</div>
    </main>
    <nav className="mobile-bottom-nav" aria-label="Primary mobile navigation">{NAV_ITEMS.filter(item => ["Overview", "People", "Giving", "Care inbox"].includes(item.label)).map(({ label, path, icon: Icon }) => <Link key={label} href={path} className={activeSection === label ? "active" : ""} data-testid={`bottom-nav-${label.toLowerCase().replace(/ /g, "-")}`} aria-current={activeSection === label ? "page" : undefined}><Icon size={21} strokeWidth={1.7} /><span>{label === "Overview" ? "Dashboard" : label === "Care inbox" ? "Care" : label}</span><i /></Link>)}<button data-testid="bottom-nav-more" className={!["Overview", "People", "Giving", "Care inbox"].includes(activeSection) ? "active" : ""} onClick={() => setMobileOpen(true)}><MoreHorizontal size={23} /><span>More</span><i /></button></nav>
    <Dialog open={mobileOpen} onOpenChange={setMobileOpen}><DialogContent className="mobile-navigation-dialog" showCloseButton={false} data-testid="mobile-navigation-dialog"><DialogTitle className="sr-only" data-testid="mobile-navigation-title">Church navigation</DialogTitle><DialogDescription className="sr-only" data-testid="mobile-navigation-description">Explore every part of your church workspace.</DialogDescription><div className="mobile-sidebar-brand">{logo("drawer")}<DialogClose className="icon-button" data-testid="mobile-menu-close" aria-label="Close navigation"><X size={21} /></DialogClose></div>{menu("drawer")}</DialogContent></Dialog>
    <Dialog open={profileOpen} onOpenChange={setProfileOpen}><DialogContent className="workspace-dialog profile-dialog" data-testid="pastor-profile-dialog"><span className="profile-avatar profile-avatar-large">DS</span><DialogTitle data-testid="pastor-profile-name">{PASTOR_NAME}</DialogTitle><DialogDescription data-testid="pastor-profile-description">Church administrator · {CHURCH_NAME}</DialogDescription><p data-testid="pastor-profile-scope">Serving one church family across Milnerton, Bellville, Eastgate, Kinshasa and Lubumbashi.</p><Link href="/member" className="button button-primary" data-testid="open-member-experience">Open member experience<ArrowUpRight size={16} /></Link></DialogContent></Dialog>
  </div>;
};