import { useState } from "react";
import { ArrowUpRight, ArrowRight, ArrowDownRight, Users, CalendarCheck, Target, HeartHandshake, ClipboardCheck, Layers3, BookOpen, Info, Download, CalendarDays, Church, GitBranch } from "lucide-react";
import { BRANCHES, compactZar, zar, TODAY, consecutiveMisses } from "@/data/demo";
import { getDashboardMetrics } from "@/data/dashboardMetrics";
import { PASTOR_NAME, type Section } from "@/data/navigation";
import { PulseChart, PulseRing } from "@/components/dashboard/PulseChart";

const upcoming = [
  { day: 14, title: "Leadership Summit", detail: "09:00 · All branches", type: "Leadership" },
  { day: 18, title: "Midweek Worship", detail: "18:30 · Milnerton", type: "Worship" },
  { day: 21, title: "Community Outreach", detail: "10:00 · Bellville", type: "Outreach" },
];
export default function ChurchOverview({ scope, onNavigate, onOpenMember }: { scope: number | "global"; onNavigate: (section: Section) => void; onOpenMember: (id: number) => void }) {
  const metrics = getDashboardMetrics(scope);
  const [weeks, setWeeks] = useState(12);
  const hour = new Date().getHours();
  const greeting = hour < 12 ? "Good morning," : hour < 17 ? "Good afternoon," : "Good evening,";
  const scopeName = scope === "global" ? "All branches" : BRANCHES[scope - 1];
  const exportReport = () => {
    const rows = [["Church overview", scopeName], ["Sample data", "Congolese and South African church community"], ["Church pulse", metrics.score], ["Members", metrics.members.length], ["Sunday attendance", metrics.present], ["Giving received (ZAR)", metrics.goal.received], ["Giving goal (ZAR)", metrics.goal.pledged], ["Follow-up queue", metrics.followups.length]];
    const url = URL.createObjectURL(new Blob([rows.map(row => row.join(",")).join("\n")], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = "church-overview.csv"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <div className="church-overview" data-testid="church-overview">
    <div className="overview-utility"><span className="eyebrow" data-testid="dashboard-eyebrow">YOUR CHURCH, AT A GLANCE</span><div><span className="overview-date" data-testid="overview-date"><CalendarDays size={14} />{TODAY.toLocaleDateString("en-ZA", { day: "numeric", month: "long", year: "numeric" })}</span><button className="button button-ghost" data-testid="export-overview-report" onClick={exportReport}><Download size={15} /><span>Export overview</span></button></div></div>
    <section className="welcome-pulse" aria-label="Church overview greeting"><div className="welcome-pulse-copy"><p className="welcome-greeting" data-testid="dashboard-greeting">{greeting}</p><h1 data-testid="pastor-greeting-name">{PASTOR_NAME}<span className="greeting-dot" aria-hidden="true">.</span></h1><p className="welcome-description" data-testid="dashboard-welcome-description">A clear view of your church. More room to care.</p><span className="welcome-context" data-testid="dashboard-scope"><span className="tiny-dot" />{scopeName} <span>·</span> One church family</span></div><div className="pulse-wrapper"><PulseRing score={metrics.score} /><details className="pulse-explanation"><summary data-testid="pulse-score-info" aria-label="How the church pulse is calculated"><Info size={12} />About your score</summary><p data-testid="pulse-score-explanation">A sample participation indicator: attendance rate (50%), active membership (30%) and giving goal progress (20%). Not an assessment of individual faith.</p></details></div></section>
    <div className="hero-trend"><PulseChart values={metrics.attendance} compact testId="hero-attendance-sparkline" /><div className="hero-trend-caption" data-testid="hero-trend-caption"><span>Small steps. A growing community.</span><span>12-week attendance rhythm</span></div></div>
    <section className="pulse-metrics" aria-label="Key church metrics">{[
      { id: "members", icon: Users, value: metrics.members.length, label: "Church family", caption: scope === "global" ? "Across 5 branches" : `${scopeName} branch` },
      { id: "attendance", icon: CalendarCheck, value: metrics.present, label: "Sunday attendance", caption: `${metrics.attendanceRate}% of members` },
      { id: "goal", icon: Target, value: `${metrics.goalProgress}%`, label: "Giving goal", caption: `${compactZar(metrics.goal.received)} received` },
      { id: "followups", icon: HeartHandshake, value: metrics.followups.length, label: "Care follow-ups", caption: "A personal touch" },
    ].map(({ id, icon: Icon, value, label, caption }) => <div className="pulse-metric" key={id} data-testid={`dashboard-metric-${id}`}><div className="pulse-metric-value"><Icon size={19} strokeWidth={1.6} /><strong data-testid={`dashboard-value-${id}`}>{value}</strong></div><span data-testid={`dashboard-label-${id}`}>{label}</span><small data-testid={`dashboard-caption-${id}`}>{caption}</small></div>)}</section>
    <div className="overview-primary-grid"><section className="giving-goal-card" data-testid="giving-goal-card"><div className="giving-goal-main"><div className="eyebrow" data-testid="giving-goal-eyebrow">GIVING WITH PURPOSE</div><h2 data-testid="giving-goal-title">{metrics.goal.title}</h2><strong className="giving-goal-amount" data-testid="giving-goal-amount">{zar(metrics.goal.received)}</strong><p data-testid="giving-goal-description">Every contribution helps the vision grow.</p><div className="giving-goal-track" role="progressbar" aria-label="Giving goal progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={metrics.goalProgress} data-testid="giving-goal-progress"><span style={{ width: `${Math.min(metrics.goalProgress, 100)}%` }}><i /></span></div><div className="giving-goal-progress-copy" data-testid="giving-goal-progress-copy"><span>Goal: {zar(metrics.goal.pledged)}</span><strong>{metrics.goalProgress}% achieved</strong></div></div><div className="giving-goal-art"><span className="giving-performance" data-testid="giving-goal-badge"><ArrowUpRight size={13} />Building together</span><svg viewBox="0 0 280 150" role="img" aria-label="Illustration of shared giving progress"><path d="M0 142 45 116 82 126 130 70 172 91 216 33 280 0 280 150 0 150Z" fill="var(--accent)" opacity=".06" /><path d="M0 150 55 130 103 144 153 83 190 98 233 54 280 30 280 150Z" fill="var(--accent)" opacity=".09" /><path d="M0 150 60 145 105 137 155 118 197 132 245 72 280 53 280 150Z" fill="var(--accent)" opacity=".12" /><path d="M0 142 45 116 82 126 130 70 172 91 216 33 280 0" fill="none" stroke="var(--accent)" opacity=".28" strokeWidth="1.5" /></svg><button className="text-button" data-testid="view-giving-goals" onClick={() => onNavigate("Projects")}>View projects<ArrowRight size={15} /></button></div></section>
    <section className="care-recommendation" data-testid="care-recommendation"><div className="care-recommendation-heading"><span className="care-recommendation-icon"><HeartHandshake size={23} strokeWidth={1.6} /></span><span className="eyebrow" data-testid="care-recommendation-eyebrow">A LITTLE CARE GOES A LONG WAY</span></div><h2 data-testid="care-recommendation-title">{metrics.followups.length ? `${metrics.followups.length} people. A chance to reconnect.` : "Your church family is connected."}</h2><p data-testid="care-recommendation-description">{metrics.followups.length ? "These members have missed 3 or more Sundays. A thoughtful check-in can make all the difference." : "Keep making space for a personal word of encouragement."}</p><button className="button care-recommendation-button" data-testid="review-followups-button" onClick={() => onNavigate("Care inbox")}>Open care inbox<ArrowRight size={16} /></button></section></div>
    <section className="ministry-quick-section"><div className="section-heading"><h2 data-testid="quick-actions-title">Make a little more possible.</h2><span className="eyebrow" data-testid="quick-actions-label">QUICK ACTIONS</span></div><div className="ministry-quick-grid">{[
      { title: "People", subtitle: "Know your church family", icon: Users, section: "People" }, { title: "Attendance", subtitle: "See who is connecting", icon: ClipboardCheck, section: "Attendance" }, { title: "Departments", subtitle: "Equip your ministry teams", icon: Layers3, section: "Departments" }, { title: "Sermons", subtitle: "Grow through the Word", icon: BookOpen, section: "Sermons" },
    ].map(({ title, subtitle, icon: Icon, section }) => <button key={title} className="ministry-quick-card" data-testid={`quick-action-${title.toLowerCase()}`} onClick={() => onNavigate(section as Section)}><span className="quick-card-icon"><Icon size={21} strokeWidth={1.6} /></span><div><strong>{title}</strong><span>{subtitle}</span></div><ArrowUpRight size={17} className="quick-card-arrow" /></button>)}</div></section>
    <div className="overview-detail-grid"><section className="overview-panel"><div className="section-heading"><div><div className="eyebrow" data-testid="attendance-trend-eyebrow">SHOWING UP, TOGETHER</div><h2 data-testid="attendance-trend-title">Attendance rhythm</h2></div><select className="chart-period-select" aria-label="Attendance chart period" data-testid="attendance-chart-period" value={weeks} onChange={e => setWeeks(Number(e.target.value))}><option value={12}>Last 12 weeks</option><option value={6}>Last 6 weeks</option></select></div><div className="attendance-chart-summary" data-testid="attendance-chart-summary"><strong>{metrics.present}<small>people last Sunday</small></strong><span className={metrics.change >= 0 ? "positive-change" : "neutral-change"}>{metrics.change >= 0 ? <ArrowUpRight size={15} /> : <ArrowDownRight size={15} />}{Math.abs(metrics.change)}% <small>vs previous 4 weeks</small></span></div><PulseChart values={metrics.attendance.slice(-weeks)} /><div className="attendance-chart-axis" data-testid="attendance-chart-axis"><span>{weeks} weeks ago</span><span>Sunday gatherings</span><span>This week</span></div></section>
    <section className="overview-panel next-gatherings"><div className="section-heading"><div><div className="eyebrow" data-testid="upcoming-eyebrow">LIFE IN COMMUNITY</div><h2 data-testid="upcoming-title">Coming together</h2></div><button className="text-button" data-testid="view-all-events" onClick={() => onNavigate("Events")}>View all<ArrowUpRight size={14} /></button></div>{upcoming.map((event, i) => <button className="gathering-row" key={event.title} data-testid={`upcoming-event-${i}`} onClick={() => onNavigate("Events")}><span className="gathering-date"><strong>{event.day}</strong><small>SEP</small></span><span className="gathering-info"><strong>{event.title}</strong><small>{event.detail}</small></span><ArrowRight size={15} /></button>)}<div className="gathering-footer" data-testid="gatherings-footer"><Church size={15} />There is a place for everyone.</div></section></div>
    <div className="overview-detail-grid"><section className="overview-panel"><div className="section-heading"><div><div className="eyebrow" data-testid="personal-care-eyebrow">BEHIND EVERY NUMBER, A PERSON</div><h2 data-testid="personal-care-title">A moment to reach out</h2></div><span className="small-count" data-testid="personal-care-count">{metrics.followups.length}</span></div><div>{metrics.followups.slice(0, 3).map(member => <button className="personal-care-row" key={member.id} data-testid={`care-member-${member.id}`} onClick={() => onOpenMember(member.id)}><span className="light-person-avatar">{member.initials}</span><span><strong>{member.name}</strong><small>{member.branch} · {consecutiveMisses(member.attendance)} Sundays missed</small></span><span className="care-row-link">View profile<ArrowUpRight size={14} /></span></button>)}{!metrics.followups.length && <p className="overview-empty-copy" data-testid="no-followups">No members have missed three consecutive Sundays.</p>}</div></section>
    <section className="overview-panel branch-snapshot"><div className="section-heading"><div><div className="eyebrow" data-testid="branches-eyebrow">ONE VISION. MANY COMMUNITIES.</div><h2 data-testid="branches-title">Our branches</h2></div><GitBranch size={19} /></div>{BRANCHES.filter((_, i) => scope === "global" || scope === i + 1).map(branch => { const count = metrics.members.filter(member => member.branch === branch).length; return <div className="branch-snapshot-row" key={branch} data-testid={`branch-snapshot-${branch.toLowerCase()}`}><span><i />{branch}</span><strong>{count}<small>members</small></strong></div>; })}</section></div>
    <footer className="dashboard-footer" data-testid="dashboard-footer"><span>Heirs of Promise Sanctuary</span><span>Built around people. Rooted in purpose.</span><span>Sample community data</span></footer>
  </div>;
}