import { useState } from "react";
import { ArrowUpRight, GitBranch, Plus, Search, Users, Layers3, ClipboardList, Download, ArrowRight } from "lucide-react";
import { toast } from "sonner";
import { useDepartmentWorkspace } from "@/hooks/useDepartmentWorkspace";
import { BRANCHES } from "@/data/demo";
import { FEATURE_STATUS_LABELS, type DepartmentFeature, type DepartmentWorkspace, type DepartmentInput } from "@shared/departmentFeatures";
import { DepartmentForm } from "@/components/departments/DepartmentForm";
import { RequestDialog } from "@/components/departments/RequestDialog";
import { exportDepartmentBrief } from "@/components/departments/exportBrief";

export default function DepartmentsPage({ scope, onScope }: { scope: number | "global"; onScope: (scope: number | "global") => void }) {
  const workspace = useDepartmentWorkspace();
  const [tab, setTab] = useState<"departments" | "requests">("departments");
  const [search, setSearch] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [request, setRequest] = useState<{ department: DepartmentWorkspace; feature?: DepartmentFeature } | null>(null);
  const [filter, setFilter] = useState("all");
  const visible = workspace.items.filter(dept => (scope === "global" || dept.branchId === scope) && `${dept.name} ${dept.leadName} ${BRANCHES[dept.branchId - 1]}`.toLowerCase().includes(search.toLowerCase()));
  const requests = visible.flatMap(department => department.features.map(feature => ({ department, feature })));
  const filteredRequests = requests.filter(({ feature }) => filter === "all" || feature.status === filter);
  const create = async (draft: DepartmentInput) => { await workspace.create(draft); setSearch(""); setTab("departments"); if (scope !== "global") onScope(draft.branchId); toast.success("Department created", { description: workspace.isSample ? "Feature brief saved in this browser. Export it to share with your team." : "Feature requests are ready for review." }); };
  return <section className="department-workspace" data-testid="department-workspace">
    <div className="workspace-page-heading"><div><div className="eyebrow" data-testid="departments-eyebrow">PEOPLE WITH PURPOSE</div><h1 data-testid="departments-title">Every ministry, connected.</h1><p data-testid="departments-description">Build your teams. Tell us what they need. Make room for meaningful work.</p></div><button className="button button-primary" data-testid="create-department-button" disabled={!workspace.canManage || workspace.loading} onClick={() => setCreateOpen(true)}><Plus size={17} />Add department</button></div>
    {workspace.isSample && <p className="sample-storage-note" data-testid="department-sample-note">Sample workspace · Department changes are saved in this browser. Export a brief to share with your development team.</p>}
    <div className="department-summary-grid">{[
      { title: "Departments", value: visible.length, icon: Layers3 },
      { title: "People serving", value: visible.reduce((sum, dept) => sum + dept.memberCount, 0), icon: Users },
      { title: "Feature requests", value: requests.length, icon: ClipboardList },
    ].map(({ title, value, icon: Icon }, i) => <div className="department-summary" key={title} data-testid={`department-summary-${i}`}><span className="soft-icon"><Icon size={20} /></span><div><strong>{value}</strong><span>{title}</span></div></div>)}</div>
    <div className="department-workspace-toolbar"><div className="workspace-tabs" role="tablist" aria-label="Department workspace"><button role="tab" aria-selected={tab === "departments"} className={tab === "departments" ? "selected" : ""} data-testid="departments-tab" onClick={() => setTab("departments")}>Departments</button><button role="tab" aria-selected={tab === "requests"} className={tab === "requests" ? "selected" : ""} data-testid="requests-tab" onClick={() => setTab("requests")}>Feature requests <span>{requests.length}</span></button></div><button className="button button-ghost" data-testid="export-department-briefs" disabled={!visible.length} onClick={() => exportDepartmentBrief(visible, workspace.isSample)}><Download size={15} />Export briefs</button></div>
    <div className="department-filter-row"><label className="search-field"><Search size={17} /><input aria-label="Search departments" data-testid="department-search-input" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search departments or leaders…" /></label><span className="scope-caption" data-testid="departments-current-branch"><GitBranch size={14} />{scope === "global" ? "Across all 5 branches" : BRANCHES[scope - 1]}</span>{tab === "requests" && <select aria-label="Filter request status" data-testid="request-status-filter" className="request-filter" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All statuses</option>{Object.entries(FEATURE_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>}</div>
    {workspace.loading ? <div className="workspace-empty" role="status" data-testid="departments-loading">Opening your departments…</div> : workspace.error ? <div className="workspace-empty" role="alert" data-testid="departments-error"><p>We couldn't load your shared workspace. {workspace.error.message}</p><button data-testid="departments-retry" className="button button-ghost" onClick={() => workspace.retry()}>Try again</button></div> : !workspace.canManage ? <div className="workspace-empty" data-testid="departments-permission-note">Your church administrator manages departments and feature requests.</div> : tab === "departments" ?
      <div className="ministry-grid">{visible.map((department, i) => <article className="ministry-card" key={department.id} data-testid={`department-card-${department.id}`} style={{ animationDelay: `${i * 40}ms` }}>
        <div className="ministry-card-top"><span className={`ministry-monogram tone-${i % 3}`} aria-hidden="true">{department.name.split(/\s|&/).filter(Boolean).slice(0, 2).map(word => word[0]).join("")}</span><span className="ministry-branch" data-testid={`department-branch-${department.id}`}><GitBranch size={12} />{BRANCHES[department.branchId - 1]}</span></div>
        <h2 data-testid={`department-name-${department.id}`}>{department.name}</h2><p className="ministry-purpose" data-testid={`department-purpose-${department.id}`}>{department.description || "A new chapter of ministry, service and connection."}</p>
        <div className="ministry-leader" data-testid={`department-leader-${department.id}`}><span className="mini-person" aria-hidden="true">{department.leadName.split(" ").slice(0, 2).map(word => word[0]).join("")}</span><div><span>Department leader</span><strong>{department.leadName}</strong></div></div>
        <div className="ministry-card-meta" data-testid={`department-counts-${department.id}`}><span><Users size={14} />{department.memberCount} people</span><button className="text-button" data-testid={`view-department-requests-${department.id}`} onClick={() => { setSearch(department.name); setTab("requests"); setFilter("all"); }}>{department.features.length} requests<ArrowUpRight size={14} /></button></div>
        <button className="request-feature-button" data-testid={`request-department-feature-${department.id}`} onClick={() => setRequest({ department })}><Plus size={15} />Request a feature<ArrowRight size={15} /></button>
      </article>)}<button className="ministry-add-card" data-testid="department-add-card" onClick={() => setCreateOpen(true)}><span className="add-circle"><Plus size={22} /></span><strong>Start something meaningful</strong><span>Add a department and define the tools your team needs.</span></button></div> :
      <div className="feature-request-list" data-testid="feature-request-list">{filteredRequests.map(({ department, feature }) => <button className="feature-request-row" key={`${department.id}-${feature.id}`} data-testid={`feature-request-${feature.id}`} onClick={() => setRequest({ department, feature })}><span className="soft-icon"><ClipboardList size={19} /></span><div className="feature-request-info"><strong data-testid={`feature-request-title-${feature.id}`}>{feature.title}</strong><span>{department.name} · {BRANCHES[department.branchId - 1]}</span></div><span className={`priority-tag priority-${feature.priority}`}>{feature.priority}</span><span className={`request-status request-status-${feature.status}`} data-testid={`feature-request-status-${feature.id}`}>{FEATURE_STATUS_LABELS[feature.status]}</span><ArrowUpRight size={18} /></button>)}{!filteredRequests.length && <div className="workspace-empty" data-testid="no-feature-requests"><ClipboardList size={26} /><h2>No requests here yet.</h2><p>Open a department to describe the features your team needs.</p><button className="button button-ghost" data-testid="back-to-departments" onClick={() => { setTab("departments"); setSearch(""); }}>Explore departments</button></div>}</div>}
    <div className="development-note" data-testid="development-process-note"><ClipboardList size={22} /><div><strong>Your ministry shapes what we build.</strong><p>Describe your need → share the brief → the development team reviews and builds it. No AI, no automatic code changes.</p></div></div>
    {createOpen && <DepartmentForm open onClose={() => setCreateOpen(false)} onSave={create} pending={workspace.pending} branchId={scope === "global" ? 1 : scope} isSample={workspace.isSample} />}
    {request && <RequestDialog departmentName={request.department.name} feature={request.feature} onClose={() => setRequest(null)} pending={workspace.pending} onAdd={input => workspace.addFeature(request.department.id, input)} onUpdate={workspace.updateFeature} />}
  </section>;
}