import { useState } from "react";
import { CalendarDays, Check, ChevronRight, CircleDollarSign, Download, HeartHandshake, Smartphone, Sparkles } from "lucide-react";
import { toast } from "sonner";

export default function MemberHome() {
  const [response, setResponse] = useState<string | null>(null);
  const declare = (value: string) => { setResponse(value); toast.success("Attendance response saved", { description: value }); };
  return <div className="member-app"><div className="member-app-top"><div className="brand"><span className="brand-mark"><span /></span><div><strong>ChurchFlow</strong><span>MEMBER APP</span></div></div><button className="member-install" onClick={() => toast.info("Install from your browser menu", { description: "Choose Add to Home Screen or Install ChurchFlow." })}><Download size={15} />Install app</button></div><main className="member-app-content"><div className="member-welcome"><div><div className="eyebrow">LIVING HOPE ASSEMBLY</div><h1>Good morning, Amaka</h1><p>Stay close to your church family. Your response helps us prepare a place for you.</p></div><span className="member-spark"><Sparkles size={19} /></span></div><section className="member-card featured-member-card"><div className="member-card-top"><div><div className="eyebrow">THIS SUNDAY · JUNE 30</div><h2>Worship service</h2></div><CalendarDays size={19} /></div><p>10:00 AM · Main auditorium and online</p><div className="member-response-grid"><button className={response === "attending" ? "member-response active" : "member-response"} onClick={() => declare("You’re attending in person")}>{response === "attending" && <Check size={14} />}<span>Yes, I’m coming</span></button><button className={response === "online" ? "member-response active" : "member-response"} onClick={() => declare("You’re joining online")}>{response === "online" && <Check size={14} />}<span>I’ll join online</span></button><button className={response === "not_attending" ? "member-response muted active" : "member-response muted"} onClick={() => declare("Not attending this Sunday")}>{response === "not_attending" && <Check size={14} />}<span>Not this week</span></button></div></section><section className="member-section-heading"><div><div className="eyebrow">GIVE WITH PURPOSE</div><h2>Active projects</h2></div><button>View all <ChevronRight size={14} /></button></section><section className="member-project-card"><div className="member-project-icon"><CircleDollarSign size={19} /></div><div className="member-project-body"><h3>New auditorium chairs</h3><p>Help us make room for more people.</p><div className="member-project-progress"><div><span style={{ width: "64%" }} /></div><b>64%</b></div><small>₦2.86M of ₦4.5M raised</small></div><a href="https://paystack.com/pay/living-hope-chairs" target="_blank" rel="noreferrer"><HeartHandshake size={17} /></a></section><section className="member-help-card"><Smartphone size={18} /><div><strong>Keep ChurchFlow close</strong><span>Add this app to your home screen so attendance reminders and project updates are always one tap away.</span></div></section></main></div>;
}
